language: go

script:
- make test
- make build-all
before_deploy:
- sudo apt-get update
- sudo apt-get install -y jshon
- export BODY=$(cat ./build/CHANGELOG.md)
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - ./bin/custom-command
  - ./bin/custom-command-mac
  - ./bin/custom-command.exe
  skip_cleanup: true
  body: ${BODY}
#  on:
#    tags: true
