language: go

script:
- make test
- make build-all
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - ./bin/custom-command
  - ./bin/custom-command-mac
  - ./bin/custom-command.exe
  skip_cleanup: true
  body: $(jshon -s "$(cat build/CHANGELOG.md)"))
  on:
    tags: true
