language: go

script:
- make test
- make build-all
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - ./build/custom-command
  - ./build/custom-command-mac
  - ./build/custom-command.exe
  skip_cleanup: true
  body: "test"
  on:
    tags: true
