language: go

script:
- make test
- make build-all
before_deploy: apt-get install jshon
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - ./bin/custom-command
  - ./bin/custom-command-mac
  - ./bin/custom-command.exe
  skip_cleanup: true
  body: $(sed -e 's/^"//' -e 's/"$//' <<<$(jshon -s "$(cat ./build/CHANGELOG.md)"))
#  on:
#    tags: true
